_BASE_: [
  '../datasets/coco_detection_kaist_paired.yml',
  '../runtime_kaist.yml',
  '_base_/optimizer.yml',
  '_base_/dpdetr_r50vd.yml',
  '_base_/dpdetr_reader.yml',
]

#weights: output/rtdetr_r50vd_6x_coco/model_final
find_unused_parameters: True
log_iter: 200
